version: 4
homeassistant:
  enabled: true
advanced:
  network_key:
    - 134
    - 177
    - 71
    - 229
    - 77
    - 23
    - 9
    - 93
    - 22
    - 188
    - 212
    - 215
    - 123
    - 68
    - 41
    - 135
  pan_id: 45560
  ext_pan_id:
    - 58
    - 173
    - 77
    - 38
    - 125
    - 100
    - 111
    - 162
mqtt:
  server: mqtt://core-mosquitto:1883
  user: mqtt_user
  password: Wjehw-8238hwoahabfbN
serial:
  port: >-
    /dev/serial/by-id/usb-Nabu_Casa_SkyConnect_v1.0_fc42f8f4e99aed119cc57c08a8669f5d-if00-port0
  adapter: ezsp
frontend:
  enabled: true
  port: 8099
devices:
  '0x70c59cfffed91e79':
    friendly_name: Keittiön jouluvalo
  '0x70c59cfffee7931f':
    friendly_name: Rasia 2
  '0x0c2a6ffffe3d0da3':
    friendly_name: Rasia 3
  '0x70c59cfffebf8c4c':
    friendly_name: Rasia 4
  '0x0c2a6ffffe45c0c4':
    friendly_name: Rasia 5
  '0x70c59cfffef07d8e':
    friendly_name: Rasia 6
  '0x70c59cfffee75cf2':
    friendly_name: Rasia 7
  '0x0c2a6ffffe44fa66':
    friendly_name: Rasia 8
  '0x3410f4fffe6d2127':
    friendly_name: Olohuoneen lämpötila
  '0xa4c1382009ac9a04':
    friendly_name: Tallin lämpötila
